# Use frameworks
use_frameworks!

platform :ios, '15.0'

target 'FederatedMLApp' do
  # TensorFlow Lite for on-device inference
  pod 'TensorFlowLiteSwift', '~> 2.14.0'
  
  # Networking (if needed for more complex API calls)
  # pod 'Alamofire', '~> 5.8'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
